# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 543)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 10, 61, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 110, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 110, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 40, 511, 481))
        self.listWidget.setObjectName("listWidget")
        self.broadcasterName = QtWidgets.QLineEdit(self.centralwidget)
        self.broadcasterName.setGeometry(QtCore.QRect(20, 10, 151, 22))
        self.broadcasterName.setObjectName("broadcasterName")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(550, 150, 361, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(680, 130, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 520, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setEnabled(True)
        self.loading.setGeometry(QtCore.QRect(180, 50, 201, 21))
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.clipName = QtWidgets.QLineEdit(self.centralwidget)
        self.clipName.setGeometry(QtCore.QRect(690, 10, 211, 22))
        self.clipName.setObjectName("clipName")
        self.dateStart = QtWidgets.QDateEdit(self.centralwidget)
        self.dateStart.setGeometry(QtCore.QRect(370, 10, 110, 22))
        self.dateStart.setObjectName("dateStart")
        self.dateEnd = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEnd.setGeometry(QtCore.QRect(510, 10, 110, 22))
        self.dateEnd.setObjectName("dateEnd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 10, 16, 21))
        self.label_4.setObjectName("label_4")
        self.showClipName = QtWidgets.QLabel(self.centralwidget)
        self.showClipName.setGeometry(QtCore.QRect(550, 70, 221, 31))
        self.showClipName.setText("")
        self.showClipName.setObjectName("showClipName")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 50, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.clipImage = QtWidgets.QLabel(self.centralwidget)
        self.clipImage.setGeometry(QtCore.QRect(780, 40, 121, 61))
        self.clipImage.setObjectName("clipImage")
        self.clipgetterIcon = QtWidgets.QLabel(self.centralwidget)
        self.clipgetterIcon.setGeometry(QtCore.QRect(550, 30, 41, 51))
        self.clipgetterIcon.setObjectName("clipgetterIcon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClipGetter"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.pushButton_2.setText(_translate("MainWindow", "Get Clip Information"))
        self.pushButton_3.setText(_translate("MainWindow", "Copy Clip Link"))
        self.label.setText(_translate("MainWindow", "Clip Information"))
        self.label_2.setText(_translate("MainWindow", "Clips"))
        self.loading.setText(_translate("MainWindow", "Searching..."))
        self.label_3.setText(_translate("MainWindow", "Get clips from"))
        self.label_4.setText(_translate("MainWindow", "to"))
        self.label_6.setText(_translate("MainWindow", "Clip"))
        self.clipImage.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/noClipImage/noClipImage.jpg\"/></p></body></html>"))
        self.clipgetterIcon.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/clipgetter/clipgetter.png\"/></p></body></html>"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
import resources_rc
